services:
  db:
    image: mysql:8.4
    container_name: crud
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: crud
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root_password
    restart: always
    volumes:
      - crud-data:/var/lib/mysql
    networks:
      - crud-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: crud-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    networks:
      - crud-network
    depends_on:
      - db

networks:
  crud-network:

volumes:
  crud-data:
